### ISSUE TITLE
Where is this installed?

### ISSUE THREAD

**Issue by uberhacker** [chromebrew/crew-profile-base#1]
Great idea @saltedcoffii.  A few questions:

1. Do we just extract this in our home directory?
2. Do we need to remove any existing settings in our `~/.bashrc`?
3. Should we source `~/profile` from `~/.bashrc`?

Maybe these basic instructions should be included in README.md?

**Comment by saltedcoffii** [comment]
So I juuuust opened https://github.com/skycocker/chromebrew/pull/5481 with a basic package file. I can translate those machine-readable instructions in the package file into human readable README instructions if you like.

**Comment by saltedcoffii** [comment]
Hopefully this is resolved now.
